# Generated by Django 5.2.17 on 2026-10-01 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_marketplaceorder_marketplaceorderitem_and_more'),
        ('marketplace', '0008_productreview_purchase_reviewattachment_and_more'),
    ]

    operations = [
    ]
