# Generated by Django 5.2.17 on 2026-10-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_chatmessage_sender_listingreport_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingreport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
