# Generated by Django 6.1 on 2026-09-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Product Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Product Image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('sold_out', models.BooleanField(default=False, verbose_name='Is Sold Out')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Posted Date')),
            ],
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
