# Generated by Django 6.1 on 2026-09-17 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_listingreport'),
        ('myapp', '0003_alter_product_options_product_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myapp_product_orders', to='marketplace.product', verbose_name='Product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
